### ISSUE TITLE
Frontend is outdated

### ISSUE THREAD

**Issue by alvarolobato** [elastic/opbeans-python#12]
This application is using an old frontend that sends data to intake.opeat.com. The node js version https://github.com/elastic/opbeans has already an updated frontend with the elastic agent.

We should compile the code and update it here. The frontend service name could be changed so we separate each frontend now that we have more than one backend.

**Comment by beniwohli** [comment]
Thanks! Ideally, we'd have the uncompiled JS in this repo as well, and compile it in the docker image. I didn't want to do that in the past because I didn't want to add a whole js build pipeline (with nodejs, npm and whatnot) to the docker image. But I recently discovered multistage docker builds, with which this should be possible: install npm/node and compile the JS in the first stage, copy the compiled JS to the second stage, and go from there.

**Comment by alvarolobato** [comment]
I noticed this because I used it for the Java application. I also have a Multi-Stage docker build, but for the agent and the application code. 

If you finally do this I will add yet another stage. Although I think that maybe is easier to just refresh once in a while now that the client code is in a separate repo.

**Comment by beniwohli** [comment]
This is solved by #13
